[package]
name = "nexum-keycard-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
## nexum-apdu
nexum-apdu-core.workspace = true
nexum-apdu-macros.workspace = true
nexum-apdu-globalplatform.workspace = true
nexum-apdu-transport-pcsc.workspace = true

## keycard crates
nexum-keycard.workspace = true
nexum-keycard-signer.workspace = true

## ui
clap = { workspace = true, features = ["derive"] }

## blockchain
alloy-primitives.workspace = true
alloy-network.workspace = true
alloy-signer.workspace = true
alloy-consensus.workspace = true

## misc
tracing.workspace = true
iso7816-tlv.workspace = true
tracing-subscriber.workspace = true
coins-bip32.workspace = true
tokio = { workspace = true, features = ["full"] }
